version: "3.8"

services:

  web:
    image: nginx
    ports:
      - "8080:80"
    deploy:
      replicas: 2

  api:
    image: httpd
    deploy:
      replicas: 2

  database:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: demo
    deploy:
      replicas: 1