<!DOCTYPE html>
<html>
<head>
    <title>Greeting Example</title>
</head>
<body>

<?php
// Get current hour (0-23)
$hour = date("H");

// Determine greeting based on time
if ($hour < 12) {
    $greeting = "Good morning!";
} elseif ($hour < 18) {
    $greeting = "Good afternoon!";
} else {
    $greeting = "Good evening!";
}

// Example user name
$userName = "Visitor";
?>

<h1><?php echo $greeting; ?></h1>
<p>Welcome, <?php echo $userName; ?>! This page was generated by PHP.</p>

</body>
</html>
